
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck 
/*
 * This file exports the `Flight` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model Flight
 * 
 */
export type FlightModel = runtime.Types.Result.DefaultSelection<Prisma.$FlightPayload>

export type AggregateFlight = {
  _count: FlightCountAggregateOutputType | null
  _min: FlightMinAggregateOutputType | null
  _max: FlightMaxAggregateOutputType | null
}

export type FlightMinAggregateOutputType = {
  id: string | null
  flightNumber: string | null
  departureTime: Date | null
  arrivalTime: Date | null
  originId: string | null
  destinationId: string | null
  planeId: string | null
}

export type FlightMaxAggregateOutputType = {
  id: string | null
  flightNumber: string | null
  departureTime: Date | null
  arrivalTime: Date | null
  originId: string | null
  destinationId: string | null
  planeId: string | null
}

export type FlightCountAggregateOutputType = {
  id: number
  flightNumber: number
  departureTime: number
  arrivalTime: number
  originId: number
  destinationId: number
  planeId: number
  _all: number
}


export type FlightMinAggregateInputType = {
  id?: true
  flightNumber?: true
  departureTime?: true
  arrivalTime?: true
  originId?: true
  destinationId?: true
  planeId?: true
}

export type FlightMaxAggregateInputType = {
  id?: true
  flightNumber?: true
  departureTime?: true
  arrivalTime?: true
  originId?: true
  destinationId?: true
  planeId?: true
}

export type FlightCountAggregateInputType = {
  id?: true
  flightNumber?: true
  departureTime?: true
  arrivalTime?: true
  originId?: true
  destinationId?: true
  planeId?: true
  _all?: true
}

export type FlightAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Flight to aggregate.
   */
  where?: Prisma.FlightWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Flights to fetch.
   */
  orderBy?: Prisma.FlightOrderByWithRelationInput | Prisma.FlightOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.FlightWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Flights from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Flights.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Flights
  **/
  _count?: true | FlightCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: FlightMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: FlightMaxAggregateInputType
}

export type GetFlightAggregateType<T extends FlightAggregateArgs> = {
      [P in keyof T & keyof AggregateFlight]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateFlight[P]>
    : Prisma.GetScalarType<T[P], AggregateFlight[P]>
}




export type FlightGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.FlightWhereInput
  orderBy?: Prisma.FlightOrderByWithAggregationInput | Prisma.FlightOrderByWithAggregationInput[]
  by: Prisma.FlightScalarFieldEnum[] | Prisma.FlightScalarFieldEnum
  having?: Prisma.FlightScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: FlightCountAggregateInputType | true
  _min?: FlightMinAggregateInputType
  _max?: FlightMaxAggregateInputType
}

export type FlightGroupByOutputType = {
  id: string
  flightNumber: string
  departureTime: Date
  arrivalTime: Date
  originId: string
  destinationId: string
  planeId: string
  _count: FlightCountAggregateOutputType | null
  _min: FlightMinAggregateOutputType | null
  _max: FlightMaxAggregateOutputType | null
}

type GetFlightGroupByPayload<T extends FlightGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<FlightGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof FlightGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], FlightGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], FlightGroupByOutputType[P]>
      }
    >
  >



export type FlightWhereInput = {
  AND?: Prisma.FlightWhereInput | Prisma.FlightWhereInput[]
  OR?: Prisma.FlightWhereInput[]
  NOT?: Prisma.FlightWhereInput | Prisma.FlightWhereInput[]
  id?: Prisma.StringFilter<"Flight"> | string
  flightNumber?: Prisma.StringFilter<"Flight"> | string
  departureTime?: Prisma.DateTimeFilter<"Flight"> | Date | string
  arrivalTime?: Prisma.DateTimeFilter<"Flight"> | Date | string
  originId?: Prisma.StringFilter<"Flight"> | string
  destinationId?: Prisma.StringFilter<"Flight"> | string
  planeId?: Prisma.StringFilter<"Flight"> | string
  passengers?: Prisma.PassengerListRelationFilter
  origin?: Prisma.XOR<Prisma.AirportScalarRelationFilter, Prisma.AirportWhereInput>
  destination?: Prisma.XOR<Prisma.AirportScalarRelationFilter, Prisma.AirportWhereInput>
  plane?: Prisma.XOR<Prisma.PlaneScalarRelationFilter, Prisma.PlaneWhereInput>
}

export type FlightOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  flightNumber?: Prisma.SortOrder
  departureTime?: Prisma.SortOrder
  arrivalTime?: Prisma.SortOrder
  originId?: Prisma.SortOrder
  destinationId?: Prisma.SortOrder
  planeId?: Prisma.SortOrder
  passengers?: Prisma.PassengerOrderByRelationAggregateInput
  origin?: Prisma.AirportOrderByWithRelationInput
  destination?: Prisma.AirportOrderByWithRelationInput
  plane?: Prisma.PlaneOrderByWithRelationInput
}

export type FlightWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.FlightWhereInput | Prisma.FlightWhereInput[]
  OR?: Prisma.FlightWhereInput[]
  NOT?: Prisma.FlightWhereInput | Prisma.FlightWhereInput[]
  flightNumber?: Prisma.StringFilter<"Flight"> | string
  departureTime?: Prisma.DateTimeFilter<"Flight"> | Date | string
  arrivalTime?: Prisma.DateTimeFilter<"Flight"> | Date | string
  originId?: Prisma.StringFilter<"Flight"> | string
  destinationId?: Prisma.StringFilter<"Flight"> | string
  planeId?: Prisma.StringFilter<"Flight"> | string
  passengers?: Prisma.PassengerListRelationFilter
  origin?: Prisma.XOR<Prisma.AirportScalarRelationFilter, Prisma.AirportWhereInput>
  destination?: Prisma.XOR<Prisma.AirportScalarRelationFilter, Prisma.AirportWhereInput>
  plane?: Prisma.XOR<Prisma.PlaneScalarRelationFilter, Prisma.PlaneWhereInput>
}, "id">

export type FlightOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  flightNumber?: Prisma.SortOrder
  departureTime?: Prisma.SortOrder
  arrivalTime?: Prisma.SortOrder
  originId?: Prisma.SortOrder
  destinationId?: Prisma.SortOrder
  planeId?: Prisma.SortOrder
  _count?: Prisma.FlightCountOrderByAggregateInput
  _max?: Prisma.FlightMaxOrderByAggregateInput
  _min?: Prisma.FlightMinOrderByAggregateInput
}

export type FlightScalarWhereWithAggregatesInput = {
  AND?: Prisma.FlightScalarWhereWithAggregatesInput | Prisma.FlightScalarWhereWithAggregatesInput[]
  OR?: Prisma.FlightScalarWhereWithAggregatesInput[]
  NOT?: Prisma.FlightScalarWhereWithAggregatesInput | Prisma.FlightScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Flight"> | string
  flightNumber?: Prisma.StringWithAggregatesFilter<"Flight"> | string
  departureTime?: Prisma.DateTimeWithAggregatesFilter<"Flight"> | Date | string
  arrivalTime?: Prisma.DateTimeWithAggregatesFilter<"Flight"> | Date | string
  originId?: Prisma.StringWithAggregatesFilter<"Flight"> | string
  destinationId?: Prisma.StringWithAggregatesFilter<"Flight"> | string
  planeId?: Prisma.StringWithAggregatesFilter<"Flight"> | string
}

export type FlightCreateInput = {
  id?: string
  flightNumber: string
  departureTime: Date | string
  arrivalTime: Date | string
  passengers?: Prisma.PassengerCreateNestedManyWithoutFlightsInput
  origin: Prisma.AirportCreateNestedOneWithoutDepartingFlightsInput
  destination: Prisma.AirportCreateNestedOneWithoutArrivingFlightsInput
  plane: Prisma.PlaneCreateNestedOneWithoutFlightsInput
}

export type FlightUncheckedCreateInput = {
  id?: string
  flightNumber: string
  departureTime: Date | string
  arrivalTime: Date | string
  originId: string
  destinationId: string
  planeId: string
  passengers?: Prisma.PassengerUncheckedCreateNestedManyWithoutFlightsInput
}

export type FlightUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  flightNumber?: Prisma.StringFieldUpdateOperationsInput | string
  departureTime?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  arrivalTime?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  passengers?: Prisma.PassengerUpdateManyWithoutFlightsNestedInput
  origin?: Prisma.AirportUpdateOneRequiredWithoutDepartingFlightsNestedInput
  destination?: Prisma.AirportUpdateOneRequiredWithoutArrivingFlightsNestedInput
  plane?: Prisma.PlaneUpdateOneRequiredWithoutFlightsNestedInput
}

export type FlightUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  flightNumber?: Prisma.StringFieldUpdateOperationsInput | string
  departureTime?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  arrivalTime?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  originId?: Prisma.StringFieldUpdateOperationsInput | string
  destinationId?: Prisma.StringFieldUpdateOperationsInput | string
  planeId?: Prisma.StringFieldUpdateOperationsInput | string
  passengers?: Prisma.PassengerUncheckedUpdateManyWithoutFlightsNestedInput
}

export type FlightCreateManyInput = {
  id?: string
  flightNumber: string
  departureTime: Date | string
  arrivalTime: Date | string
  originId: string
  destinationId: string
  planeId: string
}

export type FlightUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  flightNumber?: Prisma.StringFieldUpdateOperationsInput | string
  departureTime?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  arrivalTime?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type FlightUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  flightNumber?: Prisma.StringFieldUpdateOperationsInput | string
  departureTime?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  arrivalTime?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  originId?: Prisma.StringFieldUpdateOperationsInput | string
  destinationId?: Prisma.StringFieldUpdateOperationsInput | string
  planeId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type FlightListRelationFilter = {
  every?: Prisma.FlightWhereInput
  some?: Prisma.FlightWhereInput
  none?: Prisma.FlightWhereInput
}

export type FlightOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type FlightCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  flightNumber?: Prisma.SortOrder
  departureTime?: Prisma.SortOrder
  arrivalTime?: Prisma.SortOrder
  originId?: Prisma.SortOrder
  destinationId?: Prisma.SortOrder
  planeId?: Prisma.SortOrder
}

export type FlightMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  flightNumber?: Prisma.SortOrder
  departureTime?: Prisma.SortOrder
  arrivalTime?: Prisma.SortOrder
  originId?: Prisma.SortOrder
  destinationId?: Prisma.SortOrder
  planeId?: Prisma.SortOrder
}

export type FlightMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  flightNumber?: Prisma.SortOrder
  departureTime?: Prisma.SortOrder
  arrivalTime?: Prisma.SortOrder
  originId?: Prisma.SortOrder
  destinationId?: Prisma.SortOrder
  planeId?: Prisma.SortOrder
}

export type FlightCreateNestedManyWithoutOriginInput = {
  create?: Prisma.XOR<Prisma.FlightCreateWithoutOriginInput, Prisma.FlightUncheckedCreateWithoutOriginInput> | Prisma.FlightCreateWithoutOriginInput[] | Prisma.FlightUncheckedCreateWithoutOriginInput[]
  connectOrCreate?: Prisma.FlightCreateOrConnectWithoutOriginInput | Prisma.FlightCreateOrConnectWithoutOriginInput[]
  createMany?: Prisma.FlightCreateManyOriginInputEnvelope
  connect?: Prisma.FlightWhereUniqueInput | Prisma.FlightWhereUniqueInput[]
}

export type FlightCreateNestedManyWithoutDestinationInput = {
  create?: Prisma.XOR<Prisma.FlightCreateWithoutDestinationInput, Prisma.FlightUncheckedCreateWithoutDestinationInput> | Prisma.FlightCreateWithoutDestinationInput[] | Prisma.FlightUncheckedCreateWithoutDestinationInput[]
  connectOrCreate?: Prisma.FlightCreateOrConnectWithoutDestinationInput | Prisma.FlightCreateOrConnectWithoutDestinationInput[]
  createMany?: Prisma.FlightCreateManyDestinationInputEnvelope
  connect?: Prisma.FlightWhereUniqueInput | Prisma.FlightWhereUniqueInput[]
}

export type FlightUncheckedCreateNestedManyWithoutOriginInput = {
  create?: Prisma.XOR<Prisma.FlightCreateWithoutOriginInput, Prisma.FlightUncheckedCreateWithoutOriginInput> | Prisma.FlightCreateWithoutOriginInput[] | Prisma.FlightUncheckedCreateWithoutOriginInput[]
  connectOrCreate?: Prisma.FlightCreateOrConnectWithoutOriginInput | Prisma.FlightCreateOrConnectWithoutOriginInput[]
  createMany?: Prisma.FlightCreateManyOriginInputEnvelope
  connect?: Prisma.FlightWhereUniqueInput | Prisma.FlightWhereUniqueInput[]
}

export type FlightUncheckedCreateNestedManyWithoutDestinationInput = {
  create?: Prisma.XOR<Prisma.FlightCreateWithoutDestinationInput, Prisma.FlightUncheckedCreateWithoutDestinationInput> | Prisma.FlightCreateWithoutDestinationInput[] | Prisma.FlightUncheckedCreateWithoutDestinationInput[]
  connectOrCreate?: Prisma.FlightCreateOrConnectWithoutDestinationInput | Prisma.FlightCreateOrConnectWithoutDestinationInput[]
  createMany?: Prisma.FlightCreateManyDestinationInputEnvelope
  connect?: Prisma.FlightWhereUniqueInput | Prisma.FlightWhereUniqueInput[]
}

export type FlightUpdateManyWithoutOriginNestedInput = {
  create?: Prisma.XOR<Prisma.FlightCreateWithoutOriginInput, Prisma.FlightUncheckedCreateWithoutOriginInput> | Prisma.FlightCreateWithoutOriginInput[] | Prisma.FlightUncheckedCreateWithoutOriginInput[]
  connectOrCreate?: Prisma.FlightCreateOrConnectWithoutOriginInput | Prisma.FlightCreateOrConnectWithoutOriginInput[]
  upsert?: Prisma.FlightUpsertWithWhereUniqueWithoutOriginInput | Prisma.FlightUpsertWithWhereUniqueWithoutOriginInput[]
  createMany?: Prisma.FlightCreateManyOriginInputEnvelope
  set?: Prisma.FlightWhereUniqueInput | Prisma.FlightWhereUniqueInput[]
  disconnect?: Prisma.FlightWhereUniqueInput | Prisma.FlightWhereUniqueInput[]
  delete?: Prisma.FlightWhereUniqueInput | Prisma.FlightWhereUniqueInput[]
  connect?: Prisma.FlightWhereUniqueInput | Prisma.FlightWhereUniqueInput[]
  update?: Prisma.FlightUpdateWithWhereUniqueWithoutOriginInput | Prisma.FlightUpdateWithWhereUniqueWithoutOriginInput[]
  updateMany?: Prisma.FlightUpdateManyWithWhereWithoutOriginInput | Prisma.FlightUpdateManyWithWhereWithoutOriginInput[]
  deleteMany?: Prisma.FlightScalarWhereInput | Prisma.FlightScalarWhereInput[]
}

export type FlightUpdateManyWithoutDestinationNestedInput = {
  create?: Prisma.XOR<Prisma.FlightCreateWithoutDestinationInput, Prisma.FlightUncheckedCreateWithoutDestinationInput> | Prisma.FlightCreateWithoutDestinationInput[] | Prisma.FlightUncheckedCreateWithoutDestinationInput[]
  connectOrCreate?: Prisma.FlightCreateOrConnectWithoutDestinationInput | Prisma.FlightCreateOrConnectWithoutDestinationInput[]
  upsert?: Prisma.FlightUpsertWithWhereUniqueWithoutDestinationInput | Prisma.FlightUpsertWithWhereUniqueWithoutDestinationInput[]
  createMany?: Prisma.FlightCreateManyDestinationInputEnvelope
  set?: Prisma.FlightWhereUniqueInput | Prisma.FlightWhereUniqueInput[]
  disconnect?: Prisma.FlightWhereUniqueInput | Prisma.FlightWhereUniqueInput[]
  delete?: Prisma.FlightWhereUniqueInput | Prisma.FlightWhereUniqueInput[]
  connect?: Prisma.FlightWhereUniqueInput | Prisma.FlightWhereUniqueInput[]
  update?: Prisma.FlightUpdateWithWhereUniqueWithoutDestinationInput | Prisma.FlightUpdateWithWhereUniqueWithoutDestinationInput[]
  updateMany?: Prisma.FlightUpdateManyWithWhereWithoutDestinationInput | Prisma.FlightUpdateManyWithWhereWithoutDestinationInput[]
  deleteMany?: Prisma.FlightScalarWhereInput | Prisma.FlightScalarWhereInput[]
}

export type FlightUncheckedUpdateManyWithoutOriginNestedInput = {
  create?: Prisma.XOR<Prisma.FlightCreateWithoutOriginInput, Prisma.FlightUncheckedCreateWithoutOriginInput> | Prisma.FlightCreateWithoutOriginInput[] | Prisma.FlightUncheckedCreateWithoutOriginInput[]
  connectOrCreate?: Prisma.FlightCreateOrConnectWithoutOriginInput | Prisma.FlightCreateOrConnectWithoutOriginInput[]
  upsert?: Prisma.FlightUpsertWithWhereUniqueWithoutOriginInput | Prisma.FlightUpsertWithWhereUniqueWithoutOriginInput[]
  createMany?: Prisma.FlightCreateManyOriginInputEnvelope
  set?: Prisma.FlightWhereUniqueInput | Prisma.FlightWhereUniqueInput[]
  disconnect?: Prisma.FlightWhereUniqueInput | Prisma.FlightWhereUniqueInput[]
  delete?: Prisma.FlightWhereUniqueInput | Prisma.FlightWhereUniqueInput[]
  connect?: Prisma.FlightWhereUniqueInput | Prisma.FlightWhereUniqueInput[]
  update?: Prisma.FlightUpdateWithWhereUniqueWithoutOriginInput | Prisma.FlightUpdateWithWhereUniqueWithoutOriginInput[]
  updateMany?: Prisma.FlightUpdateManyWithWhereWithoutOriginInput | Prisma.FlightUpdateManyWithWhereWithoutOriginInput[]
  deleteMany?: Prisma.FlightScalarWhereInput | Prisma.FlightScalarWhereInput[]
}

export type FlightUncheckedUpdateManyWithoutDestinationNestedInput = {
  create?: Prisma.XOR<Prisma.FlightCreateWithoutDestinationInput, Prisma.FlightUncheckedCreateWithoutDestinationInput> | Prisma.FlightCreateWithoutDestinationInput[] | Prisma.FlightUncheckedCreateWithoutDestinationInput[]
  connectOrCreate?: Prisma.FlightCreateOrConnectWithoutDestinationInput | Prisma.FlightCreateOrConnectWithoutDestinationInput[]
  upsert?: Prisma.FlightUpsertWithWhereUniqueWithoutDestinationInput | Prisma.FlightUpsertWithWhereUniqueWithoutDestinationInput[]
  createMany?: Prisma.FlightCreateManyDestinationInputEnvelope
  set?: Prisma.FlightWhereUniqueInput | Prisma.FlightWhereUniqueInput[]
  disconnect?: Prisma.FlightWhereUniqueInput | Prisma.FlightWhereUniqueInput[]
  delete?: Prisma.FlightWhereUniqueInput | Prisma.FlightWhereUniqueInput[]
  connect?: Prisma.FlightWhereUniqueInput | Prisma.FlightWhereUniqueInput[]
  update?: Prisma.FlightUpdateWithWhereUniqueWithoutDestinationInput | Prisma.FlightUpdateWithWhereUniqueWithoutDestinationInput[]
  updateMany?: Prisma.FlightUpdateManyWithWhereWithoutDestinationInput | Prisma.FlightUpdateManyWithWhereWithoutDestinationInput[]
  deleteMany?: Prisma.FlightScalarWhereInput | Prisma.FlightScalarWhereInput[]
}

export type DateTimeFieldUpdateOperationsInput = {
  set?: Date | string
}

export type FlightCreateNestedManyWithoutPassengersInput = {
  create?: Prisma.XOR<Prisma.FlightCreateWithoutPassengersInput, Prisma.FlightUncheckedCreateWithoutPassengersInput> | Prisma.FlightCreateWithoutPassengersInput[] | Prisma.FlightUncheckedCreateWithoutPassengersInput[]
  connectOrCreate?: Prisma.FlightCreateOrConnectWithoutPassengersInput | Prisma.FlightCreateOrConnectWithoutPassengersInput[]
  connect?: Prisma.FlightWhereUniqueInput | Prisma.FlightWhereUniqueInput[]
}

export type FlightUncheckedCreateNestedManyWithoutPassengersInput = {
  create?: Prisma.XOR<Prisma.FlightCreateWithoutPassengersInput, Prisma.FlightUncheckedCreateWithoutPassengersInput> | Prisma.FlightCreateWithoutPassengersInput[] | Prisma.FlightUncheckedCreateWithoutPassengersInput[]
  connectOrCreate?: Prisma.FlightCreateOrConnectWithoutPassengersInput | Prisma.FlightCreateOrConnectWithoutPassengersInput[]
  connect?: Prisma.FlightWhereUniqueInput | Prisma.FlightWhereUniqueInput[]
}

export type FlightUpdateManyWithoutPassengersNestedInput = {
  create?: Prisma.XOR<Prisma.FlightCreateWithoutPassengersInput, Prisma.FlightUncheckedCreateWithoutPassengersInput> | Prisma.FlightCreateWithoutPassengersInput[] | Prisma.FlightUncheckedCreateWithoutPassengersInput[]
  connectOrCreate?: Prisma.FlightCreateOrConnectWithoutPassengersInput | Prisma.FlightCreateOrConnectWithoutPassengersInput[]
  upsert?: Prisma.FlightUpsertWithWhereUniqueWithoutPassengersInput | Prisma.FlightUpsertWithWhereUniqueWithoutPassengersInput[]
  set?: Prisma.FlightWhereUniqueInput | Prisma.FlightWhereUniqueInput[]
  disconnect?: Prisma.FlightWhereUniqueInput | Prisma.FlightWhereUniqueInput[]
  delete?: Prisma.FlightWhereUniqueInput | Prisma.FlightWhereUniqueInput[]
  connect?: Prisma.FlightWhereUniqueInput | Prisma.FlightWhereUniqueInput[]
  update?: Prisma.FlightUpdateWithWhereUniqueWithoutPassengersInput | Prisma.FlightUpdateWithWhereUniqueWithoutPassengersInput[]
  updateMany?: Prisma.FlightUpdateManyWithWhereWithoutPassengersInput | Prisma.FlightUpdateManyWithWhereWithoutPassengersInput[]
  deleteMany?: Prisma.FlightScalarWhereInput | Prisma.FlightScalarWhereInput[]
}

export type FlightUncheckedUpdateManyWithoutPassengersNestedInput = {
  create?: Prisma.XOR<Prisma.FlightCreateWithoutPassengersInput, Prisma.FlightUncheckedCreateWithoutPassengersInput> | Prisma.FlightCreateWithoutPassengersInput[] | Prisma.FlightUncheckedCreateWithoutPassengersInput[]
  connectOrCreate?: Prisma.FlightCreateOrConnectWithoutPassengersInput | Prisma.FlightCreateOrConnectWithoutPassengersInput[]
  upsert?: Prisma.FlightUpsertWithWhereUniqueWithoutPassengersInput | Prisma.FlightUpsertWithWhereUniqueWithoutPassengersInput[]
  set?: Prisma.FlightWhereUniqueInput | Prisma.FlightWhereUniqueInput[]
  disconnect?: Prisma.FlightWhereUniqueInput | Prisma.FlightWhereUniqueInput[]
  delete?: Prisma.FlightWhereUniqueInput | Prisma.FlightWhereUniqueInput[]
  connect?: Prisma.FlightWhereUniqueInput | Prisma.FlightWhereUniqueInput[]
  update?: Prisma.FlightUpdateWithWhereUniqueWithoutPassengersInput | Prisma.FlightUpdateWithWhereUniqueWithoutPassengersInput[]
  updateMany?: Prisma.FlightUpdateManyWithWhereWithoutPassengersInput | Prisma.FlightUpdateManyWithWhereWithoutPassengersInput[]
  deleteMany?: Prisma.FlightScalarWhereInput | Prisma.FlightScalarWhereInput[]
}

export type FlightCreateNestedManyWithoutPlaneInput = {
  create?: Prisma.XOR<Prisma.FlightCreateWithoutPlaneInput, Prisma.FlightUncheckedCreateWithoutPlaneInput> | Prisma.FlightCreateWithoutPlaneInput[] | Prisma.FlightUncheckedCreateWithoutPlaneInput[]
  connectOrCreate?: Prisma.FlightCreateOrConnectWithoutPlaneInput | Prisma.FlightCreateOrConnectWithoutPlaneInput[]
  createMany?: Prisma.FlightCreateManyPlaneInputEnvelope
  connect?: Prisma.FlightWhereUniqueInput | Prisma.FlightWhereUniqueInput[]
}

export type FlightUncheckedCreateNestedManyWithoutPlaneInput = {
  create?: Prisma.XOR<Prisma.FlightCreateWithoutPlaneInput, Prisma.FlightUncheckedCreateWithoutPlaneInput> | Prisma.FlightCreateWithoutPlaneInput[] | Prisma.FlightUncheckedCreateWithoutPlaneInput[]
  connectOrCreate?: Prisma.FlightCreateOrConnectWithoutPlaneInput | Prisma.FlightCreateOrConnectWithoutPlaneInput[]
  createMany?: Prisma.FlightCreateManyPlaneInputEnvelope
  connect?: Prisma.FlightWhereUniqueInput | Prisma.FlightWhereUniqueInput[]
}

export type FlightUpdateManyWithoutPlaneNestedInput = {
  create?: Prisma.XOR<Prisma.FlightCreateWithoutPlaneInput, Prisma.FlightUncheckedCreateWithoutPlaneInput> | Prisma.FlightCreateWithoutPlaneInput[] | Prisma.FlightUncheckedCreateWithoutPlaneInput[]
  connectOrCreate?: Prisma.FlightCreateOrConnectWithoutPlaneInput | Prisma.FlightCreateOrConnectWithoutPlaneInput[]
  upsert?: Prisma.FlightUpsertWithWhereUniqueWithoutPlaneInput | Prisma.FlightUpsertWithWhereUniqueWithoutPlaneInput[]
  createMany?: Prisma.FlightCreateManyPlaneInputEnvelope
  set?: Prisma.FlightWhereUniqueInput | Prisma.FlightWhereUniqueInput[]
  disconnect?: Prisma.FlightWhereUniqueInput | Prisma.FlightWhereUniqueInput[]
  delete?: Prisma.FlightWhereUniqueInput | Prisma.FlightWhereUniqueInput[]
  connect?: Prisma.FlightWhereUniqueInput | Prisma.FlightWhereUniqueInput[]
  update?: Prisma.FlightUpdateWithWhereUniqueWithoutPlaneInput | Prisma.FlightUpdateWithWhereUniqueWithoutPlaneInput[]
  updateMany?: Prisma.FlightUpdateManyWithWhereWithoutPlaneInput | Prisma.FlightUpdateManyWithWhereWithoutPlaneInput[]
  deleteMany?: Prisma.FlightScalarWhereInput | Prisma.FlightScalarWhereInput[]
}

export type FlightUncheckedUpdateManyWithoutPlaneNestedInput = {
  create?: Prisma.XOR<Prisma.FlightCreateWithoutPlaneInput, Prisma.FlightUncheckedCreateWithoutPlaneInput> | Prisma.FlightCreateWithoutPlaneInput[] | Prisma.FlightUncheckedCreateWithoutPlaneInput[]
  connectOrCreate?: Prisma.FlightCreateOrConnectWithoutPlaneInput | Prisma.FlightCreateOrConnectWithoutPlaneInput[]
  upsert?: Prisma.FlightUpsertWithWhereUniqueWithoutPlaneInput | Prisma.FlightUpsertWithWhereUniqueWithoutPlaneInput[]
  createMany?: Prisma.FlightCreateManyPlaneInputEnvelope
  set?: Prisma.FlightWhereUniqueInput | Prisma.FlightWhereUniqueInput[]
  disconnect?: Prisma.FlightWhereUniqueInput | Prisma.FlightWhereUniqueInput[]
  delete?: Prisma.FlightWhereUniqueInput | Prisma.FlightWhereUniqueInput[]
  connect?: Prisma.FlightWhereUniqueInput | Prisma.FlightWhereUniqueInput[]
  update?: Prisma.FlightUpdateWithWhereUniqueWithoutPlaneInput | Prisma.FlightUpdateWithWhereUniqueWithoutPlaneInput[]
  updateMany?: Prisma.FlightUpdateManyWithWhereWithoutPlaneInput | Prisma.FlightUpdateManyWithWhereWithoutPlaneInput[]
  deleteMany?: Prisma.FlightScalarWhereInput | Prisma.FlightScalarWhereInput[]
}

export type FlightCreateWithoutOriginInput = {
  id?: string
  flightNumber: string
  departureTime: Date | string
  arrivalTime: Date | string
  passengers?: Prisma.PassengerCreateNestedManyWithoutFlightsInput
  destination: Prisma.AirportCreateNestedOneWithoutArrivingFlightsInput
  plane: Prisma.PlaneCreateNestedOneWithoutFlightsInput
}

export type FlightUncheckedCreateWithoutOriginInput = {
  id?: string
  flightNumber: string
  departureTime: Date | string
  arrivalTime: Date | string
  destinationId: string
  planeId: string
  passengers?: Prisma.PassengerUncheckedCreateNestedManyWithoutFlightsInput
}

export type FlightCreateOrConnectWithoutOriginInput = {
  where: Prisma.FlightWhereUniqueInput
  create: Prisma.XOR<Prisma.FlightCreateWithoutOriginInput, Prisma.FlightUncheckedCreateWithoutOriginInput>
}

export type FlightCreateManyOriginInputEnvelope = {
  data: Prisma.FlightCreateManyOriginInput | Prisma.FlightCreateManyOriginInput[]
}

export type FlightCreateWithoutDestinationInput = {
  id?: string
  flightNumber: string
  departureTime: Date | string
  arrivalTime: Date | string
  passengers?: Prisma.PassengerCreateNestedManyWithoutFlightsInput
  origin: Prisma.AirportCreateNestedOneWithoutDepartingFlightsInput
  plane: Prisma.PlaneCreateNestedOneWithoutFlightsInput
}

export type FlightUncheckedCreateWithoutDestinationInput = {
  id?: string
  flightNumber: string
  departureTime: Date | string
  arrivalTime: Date | string
  originId: string
  planeId: string
  passengers?: Prisma.PassengerUncheckedCreateNestedManyWithoutFlightsInput
}

export type FlightCreateOrConnectWithoutDestinationInput = {
  where: Prisma.FlightWhereUniqueInput
  create: Prisma.XOR<Prisma.FlightCreateWithoutDestinationInput, Prisma.FlightUncheckedCreateWithoutDestinationInput>
}

export type FlightCreateManyDestinationInputEnvelope = {
  data: Prisma.FlightCreateManyDestinationInput | Prisma.FlightCreateManyDestinationInput[]
}

export type FlightUpsertWithWhereUniqueWithoutOriginInput = {
  where: Prisma.FlightWhereUniqueInput
  update: Prisma.XOR<Prisma.FlightUpdateWithoutOriginInput, Prisma.FlightUncheckedUpdateWithoutOriginInput>
  create: Prisma.XOR<Prisma.FlightCreateWithoutOriginInput, Prisma.FlightUncheckedCreateWithoutOriginInput>
}

export type FlightUpdateWithWhereUniqueWithoutOriginInput = {
  where: Prisma.FlightWhereUniqueInput
  data: Prisma.XOR<Prisma.FlightUpdateWithoutOriginInput, Prisma.FlightUncheckedUpdateWithoutOriginInput>
}

export type FlightUpdateManyWithWhereWithoutOriginInput = {
  where: Prisma.FlightScalarWhereInput
  data: Prisma.XOR<Prisma.FlightUpdateManyMutationInput, Prisma.FlightUncheckedUpdateManyWithoutOriginInput>
}

export type FlightScalarWhereInput = {
  AND?: Prisma.FlightScalarWhereInput | Prisma.FlightScalarWhereInput[]
  OR?: Prisma.FlightScalarWhereInput[]
  NOT?: Prisma.FlightScalarWhereInput | Prisma.FlightScalarWhereInput[]
  id?: Prisma.StringFilter<"Flight"> | string
  flightNumber?: Prisma.StringFilter<"Flight"> | string
  departureTime?: Prisma.DateTimeFilter<"Flight"> | Date | string
  arrivalTime?: Prisma.DateTimeFilter<"Flight"> | Date | string
  originId?: Prisma.StringFilter<"Flight"> | string
  destinationId?: Prisma.StringFilter<"Flight"> | string
  planeId?: Prisma.StringFilter<"Flight"> | string
}

export type FlightUpsertWithWhereUniqueWithoutDestinationInput = {
  where: Prisma.FlightWhereUniqueInput
  update: Prisma.XOR<Prisma.FlightUpdateWithoutDestinationInput, Prisma.FlightUncheckedUpdateWithoutDestinationInput>
  create: Prisma.XOR<Prisma.FlightCreateWithoutDestinationInput, Prisma.FlightUncheckedCreateWithoutDestinationInput>
}

export type FlightUpdateWithWhereUniqueWithoutDestinationInput = {
  where: Prisma.FlightWhereUniqueInput
  data: Prisma.XOR<Prisma.FlightUpdateWithoutDestinationInput, Prisma.FlightUncheckedUpdateWithoutDestinationInput>
}

export type FlightUpdateManyWithWhereWithoutDestinationInput = {
  where: Prisma.FlightScalarWhereInput
  data: Prisma.XOR<Prisma.FlightUpdateManyMutationInput, Prisma.FlightUncheckedUpdateManyWithoutDestinationInput>
}

export type FlightCreateWithoutPassengersInput = {
  id?: string
  flightNumber: string
  departureTime: Date | string
  arrivalTime: Date | string
  origin: Prisma.AirportCreateNestedOneWithoutDepartingFlightsInput
  destination: Prisma.AirportCreateNestedOneWithoutArrivingFlightsInput
  plane: Prisma.PlaneCreateNestedOneWithoutFlightsInput
}

export type FlightUncheckedCreateWithoutPassengersInput = {
  id?: string
  flightNumber: string
  departureTime: Date | string
  arrivalTime: Date | string
  originId: string
  destinationId: string
  planeId: string
}

export type FlightCreateOrConnectWithoutPassengersInput = {
  where: Prisma.FlightWhereUniqueInput
  create: Prisma.XOR<Prisma.FlightCreateWithoutPassengersInput, Prisma.FlightUncheckedCreateWithoutPassengersInput>
}

export type FlightUpsertWithWhereUniqueWithoutPassengersInput = {
  where: Prisma.FlightWhereUniqueInput
  update: Prisma.XOR<Prisma.FlightUpdateWithoutPassengersInput, Prisma.FlightUncheckedUpdateWithoutPassengersInput>
  create: Prisma.XOR<Prisma.FlightCreateWithoutPassengersInput, Prisma.FlightUncheckedCreateWithoutPassengersInput>
}

export type FlightUpdateWithWhereUniqueWithoutPassengersInput = {
  where: Prisma.FlightWhereUniqueInput
  data: Prisma.XOR<Prisma.FlightUpdateWithoutPassengersInput, Prisma.FlightUncheckedUpdateWithoutPassengersInput>
}

export type FlightUpdateManyWithWhereWithoutPassengersInput = {
  where: Prisma.FlightScalarWhereInput
  data: Prisma.XOR<Prisma.FlightUpdateManyMutationInput, Prisma.FlightUncheckedUpdateManyWithoutPassengersInput>
}

export type FlightCreateWithoutPlaneInput = {
  id?: string
  flightNumber: string
  departureTime: Date | string
  arrivalTime: Date | string
  passengers?: Prisma.PassengerCreateNestedManyWithoutFlightsInput
  origin: Prisma.AirportCreateNestedOneWithoutDepartingFlightsInput
  destination: Prisma.AirportCreateNestedOneWithoutArrivingFlightsInput
}

export type FlightUncheckedCreateWithoutPlaneInput = {
  id?: string
  flightNumber: string
  departureTime: Date | string
  arrivalTime: Date | string
  originId: string
  destinationId: string
  passengers?: Prisma.PassengerUncheckedCreateNestedManyWithoutFlightsInput
}

export type FlightCreateOrConnectWithoutPlaneInput = {
  where: Prisma.FlightWhereUniqueInput
  create: Prisma.XOR<Prisma.FlightCreateWithoutPlaneInput, Prisma.FlightUncheckedCreateWithoutPlaneInput>
}

export type FlightCreateManyPlaneInputEnvelope = {
  data: Prisma.FlightCreateManyPlaneInput | Prisma.FlightCreateManyPlaneInput[]
}

export type FlightUpsertWithWhereUniqueWithoutPlaneInput = {
  where: Prisma.FlightWhereUniqueInput
  update: Prisma.XOR<Prisma.FlightUpdateWithoutPlaneInput, Prisma.FlightUncheckedUpdateWithoutPlaneInput>
  create: Prisma.XOR<Prisma.FlightCreateWithoutPlaneInput, Prisma.FlightUncheckedCreateWithoutPlaneInput>
}

export type FlightUpdateWithWhereUniqueWithoutPlaneInput = {
  where: Prisma.FlightWhereUniqueInput
  data: Prisma.XOR<Prisma.FlightUpdateWithoutPlaneInput, Prisma.FlightUncheckedUpdateWithoutPlaneInput>
}

export type FlightUpdateManyWithWhereWithoutPlaneInput = {
  where: Prisma.FlightScalarWhereInput
  data: Prisma.XOR<Prisma.FlightUpdateManyMutationInput, Prisma.FlightUncheckedUpdateManyWithoutPlaneInput>
}

export type FlightCreateManyOriginInput = {
  id?: string
  flightNumber: string
  departureTime: Date | string
  arrivalTime: Date | string
  destinationId: string
  planeId: string
}

export type FlightCreateManyDestinationInput = {
  id?: string
  flightNumber: string
  departureTime: Date | string
  arrivalTime: Date | string
  originId: string
  planeId: string
}

export type FlightUpdateWithoutOriginInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  flightNumber?: Prisma.StringFieldUpdateOperationsInput | string
  departureTime?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  arrivalTime?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  passengers?: Prisma.PassengerUpdateManyWithoutFlightsNestedInput
  destination?: Prisma.AirportUpdateOneRequiredWithoutArrivingFlightsNestedInput
  plane?: Prisma.PlaneUpdateOneRequiredWithoutFlightsNestedInput
}

export type FlightUncheckedUpdateWithoutOriginInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  flightNumber?: Prisma.StringFieldUpdateOperationsInput | string
  departureTime?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  arrivalTime?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  destinationId?: Prisma.StringFieldUpdateOperationsInput | string
  planeId?: Prisma.StringFieldUpdateOperationsInput | string
  passengers?: Prisma.PassengerUncheckedUpdateManyWithoutFlightsNestedInput
}

export type FlightUncheckedUpdateManyWithoutOriginInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  flightNumber?: Prisma.StringFieldUpdateOperationsInput | string
  departureTime?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  arrivalTime?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  destinationId?: Prisma.StringFieldUpdateOperationsInput | string
  planeId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type FlightUpdateWithoutDestinationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  flightNumber?: Prisma.StringFieldUpdateOperationsInput | string
  departureTime?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  arrivalTime?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  passengers?: Prisma.PassengerUpdateManyWithoutFlightsNestedInput
  origin?: Prisma.AirportUpdateOneRequiredWithoutDepartingFlightsNestedInput
  plane?: Prisma.PlaneUpdateOneRequiredWithoutFlightsNestedInput
}

export type FlightUncheckedUpdateWithoutDestinationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  flightNumber?: Prisma.StringFieldUpdateOperationsInput | string
  departureTime?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  arrivalTime?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  originId?: Prisma.StringFieldUpdateOperationsInput | string
  planeId?: Prisma.StringFieldUpdateOperationsInput | string
  passengers?: Prisma.PassengerUncheckedUpdateManyWithoutFlightsNestedInput
}

export type FlightUncheckedUpdateManyWithoutDestinationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  flightNumber?: Prisma.StringFieldUpdateOperationsInput | string
  departureTime?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  arrivalTime?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  originId?: Prisma.StringFieldUpdateOperationsInput | string
  planeId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type FlightUpdateWithoutPassengersInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  flightNumber?: Prisma.StringFieldUpdateOperationsInput | string
  departureTime?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  arrivalTime?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  origin?: Prisma.AirportUpdateOneRequiredWithoutDepartingFlightsNestedInput
  destination?: Prisma.AirportUpdateOneRequiredWithoutArrivingFlightsNestedInput
  plane?: Prisma.PlaneUpdateOneRequiredWithoutFlightsNestedInput
}

export type FlightUncheckedUpdateWithoutPassengersInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  flightNumber?: Prisma.StringFieldUpdateOperationsInput | string
  departureTime?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  arrivalTime?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  originId?: Prisma.StringFieldUpdateOperationsInput | string
  destinationId?: Prisma.StringFieldUpdateOperationsInput | string
  planeId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type FlightUncheckedUpdateManyWithoutPassengersInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  flightNumber?: Prisma.StringFieldUpdateOperationsInput | string
  departureTime?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  arrivalTime?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  originId?: Prisma.StringFieldUpdateOperationsInput | string
  destinationId?: Prisma.StringFieldUpdateOperationsInput | string
  planeId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type FlightCreateManyPlaneInput = {
  id?: string
  flightNumber: string
  departureTime: Date | string
  arrivalTime: Date | string
  originId: string
  destinationId: string
}

export type FlightUpdateWithoutPlaneInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  flightNumber?: Prisma.StringFieldUpdateOperationsInput | string
  departureTime?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  arrivalTime?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  passengers?: Prisma.PassengerUpdateManyWithoutFlightsNestedInput
  origin?: Prisma.AirportUpdateOneRequiredWithoutDepartingFlightsNestedInput
  destination?: Prisma.AirportUpdateOneRequiredWithoutArrivingFlightsNestedInput
}

export type FlightUncheckedUpdateWithoutPlaneInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  flightNumber?: Prisma.StringFieldUpdateOperationsInput | string
  departureTime?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  arrivalTime?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  originId?: Prisma.StringFieldUpdateOperationsInput | string
  destinationId?: Prisma.StringFieldUpdateOperationsInput | string
  passengers?: Prisma.PassengerUncheckedUpdateManyWithoutFlightsNestedInput
}

export type FlightUncheckedUpdateManyWithoutPlaneInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  flightNumber?: Prisma.StringFieldUpdateOperationsInput | string
  departureTime?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  arrivalTime?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  originId?: Prisma.StringFieldUpdateOperationsInput | string
  destinationId?: Prisma.StringFieldUpdateOperationsInput | string
}


/**
 * Count Type FlightCountOutputType
 */

export type FlightCountOutputType = {
  passengers: number
}

export type FlightCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  passengers?: boolean | FlightCountOutputTypeCountPassengersArgs
}

/**
 * FlightCountOutputType without action
 */
export type FlightCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FlightCountOutputType
   */
  select?: Prisma.FlightCountOutputTypeSelect<ExtArgs> | null
}

/**
 * FlightCountOutputType without action
 */
export type FlightCountOutputTypeCountPassengersArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.PassengerWhereInput
}


export type FlightSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  flightNumber?: boolean
  departureTime?: boolean
  arrivalTime?: boolean
  originId?: boolean
  destinationId?: boolean
  planeId?: boolean
  passengers?: boolean | Prisma.Flight$passengersArgs<ExtArgs>
  origin?: boolean | Prisma.AirportDefaultArgs<ExtArgs>
  destination?: boolean | Prisma.AirportDefaultArgs<ExtArgs>
  plane?: boolean | Prisma.PlaneDefaultArgs<ExtArgs>
  _count?: boolean | Prisma.FlightCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["flight"]>

export type FlightSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  flightNumber?: boolean
  departureTime?: boolean
  arrivalTime?: boolean
  originId?: boolean
  destinationId?: boolean
  planeId?: boolean
  origin?: boolean | Prisma.AirportDefaultArgs<ExtArgs>
  destination?: boolean | Prisma.AirportDefaultArgs<ExtArgs>
  plane?: boolean | Prisma.PlaneDefaultArgs<ExtArgs>
}, ExtArgs["result"]["flight"]>

export type FlightSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  flightNumber?: boolean
  departureTime?: boolean
  arrivalTime?: boolean
  originId?: boolean
  destinationId?: boolean
  planeId?: boolean
  origin?: boolean | Prisma.AirportDefaultArgs<ExtArgs>
  destination?: boolean | Prisma.AirportDefaultArgs<ExtArgs>
  plane?: boolean | Prisma.PlaneDefaultArgs<ExtArgs>
}, ExtArgs["result"]["flight"]>

export type FlightSelectScalar = {
  id?: boolean
  flightNumber?: boolean
  departureTime?: boolean
  arrivalTime?: boolean
  originId?: boolean
  destinationId?: boolean
  planeId?: boolean
}

export type FlightOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "flightNumber" | "departureTime" | "arrivalTime" | "originId" | "destinationId" | "planeId", ExtArgs["result"]["flight"]>
export type FlightInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  passengers?: boolean | Prisma.Flight$passengersArgs<ExtArgs>
  origin?: boolean | Prisma.AirportDefaultArgs<ExtArgs>
  destination?: boolean | Prisma.AirportDefaultArgs<ExtArgs>
  plane?: boolean | Prisma.PlaneDefaultArgs<ExtArgs>
  _count?: boolean | Prisma.FlightCountOutputTypeDefaultArgs<ExtArgs>
}
export type FlightIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  origin?: boolean | Prisma.AirportDefaultArgs<ExtArgs>
  destination?: boolean | Prisma.AirportDefaultArgs<ExtArgs>
  plane?: boolean | Prisma.PlaneDefaultArgs<ExtArgs>
}
export type FlightIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  origin?: boolean | Prisma.AirportDefaultArgs<ExtArgs>
  destination?: boolean | Prisma.AirportDefaultArgs<ExtArgs>
  plane?: boolean | Prisma.PlaneDefaultArgs<ExtArgs>
}

export type $FlightPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Flight"
  objects: {
    passengers: Prisma.$PassengerPayload<ExtArgs>[]
    origin: Prisma.$AirportPayload<ExtArgs>
    destination: Prisma.$AirportPayload<ExtArgs>
    plane: Prisma.$PlanePayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    flightNumber: string
    departureTime: Date
    arrivalTime: Date
    originId: string
    destinationId: string
    planeId: string
  }, ExtArgs["result"]["flight"]>
  composites: {}
}

export type FlightGetPayload<S extends boolean | null | undefined | FlightDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$FlightPayload, S>

export type FlightCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<FlightFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: FlightCountAggregateInputType | true
  }

export interface FlightDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Flight'], meta: { name: 'Flight' } }
  /**
   * Find zero or one Flight that matches the filter.
   * @param {FlightFindUniqueArgs} args - Arguments to find a Flight
   * @example
   * // Get one Flight
   * const flight = await prisma.flight.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends FlightFindUniqueArgs>(args: Prisma.SelectSubset<T, FlightFindUniqueArgs<ExtArgs>>): Prisma.Prisma__FlightClient<runtime.Types.Result.GetResult<Prisma.$FlightPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Flight that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {FlightFindUniqueOrThrowArgs} args - Arguments to find a Flight
   * @example
   * // Get one Flight
   * const flight = await prisma.flight.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends FlightFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, FlightFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__FlightClient<runtime.Types.Result.GetResult<Prisma.$FlightPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Flight that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FlightFindFirstArgs} args - Arguments to find a Flight
   * @example
   * // Get one Flight
   * const flight = await prisma.flight.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends FlightFindFirstArgs>(args?: Prisma.SelectSubset<T, FlightFindFirstArgs<ExtArgs>>): Prisma.Prisma__FlightClient<runtime.Types.Result.GetResult<Prisma.$FlightPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Flight that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FlightFindFirstOrThrowArgs} args - Arguments to find a Flight
   * @example
   * // Get one Flight
   * const flight = await prisma.flight.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends FlightFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, FlightFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__FlightClient<runtime.Types.Result.GetResult<Prisma.$FlightPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Flights that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FlightFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Flights
   * const flights = await prisma.flight.findMany()
   * 
   * // Get first 10 Flights
   * const flights = await prisma.flight.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const flightWithIdOnly = await prisma.flight.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends FlightFindManyArgs>(args?: Prisma.SelectSubset<T, FlightFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FlightPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Flight.
   * @param {FlightCreateArgs} args - Arguments to create a Flight.
   * @example
   * // Create one Flight
   * const Flight = await prisma.flight.create({
   *   data: {
   *     // ... data to create a Flight
   *   }
   * })
   * 
   */
  create<T extends FlightCreateArgs>(args: Prisma.SelectSubset<T, FlightCreateArgs<ExtArgs>>): Prisma.Prisma__FlightClient<runtime.Types.Result.GetResult<Prisma.$FlightPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Flights.
   * @param {FlightCreateManyArgs} args - Arguments to create many Flights.
   * @example
   * // Create many Flights
   * const flight = await prisma.flight.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends FlightCreateManyArgs>(args?: Prisma.SelectSubset<T, FlightCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Flights and returns the data saved in the database.
   * @param {FlightCreateManyAndReturnArgs} args - Arguments to create many Flights.
   * @example
   * // Create many Flights
   * const flight = await prisma.flight.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Flights and only return the `id`
   * const flightWithIdOnly = await prisma.flight.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends FlightCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, FlightCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FlightPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Flight.
   * @param {FlightDeleteArgs} args - Arguments to delete one Flight.
   * @example
   * // Delete one Flight
   * const Flight = await prisma.flight.delete({
   *   where: {
   *     // ... filter to delete one Flight
   *   }
   * })
   * 
   */
  delete<T extends FlightDeleteArgs>(args: Prisma.SelectSubset<T, FlightDeleteArgs<ExtArgs>>): Prisma.Prisma__FlightClient<runtime.Types.Result.GetResult<Prisma.$FlightPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Flight.
   * @param {FlightUpdateArgs} args - Arguments to update one Flight.
   * @example
   * // Update one Flight
   * const flight = await prisma.flight.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends FlightUpdateArgs>(args: Prisma.SelectSubset<T, FlightUpdateArgs<ExtArgs>>): Prisma.Prisma__FlightClient<runtime.Types.Result.GetResult<Prisma.$FlightPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Flights.
   * @param {FlightDeleteManyArgs} args - Arguments to filter Flights to delete.
   * @example
   * // Delete a few Flights
   * const { count } = await prisma.flight.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends FlightDeleteManyArgs>(args?: Prisma.SelectSubset<T, FlightDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Flights.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FlightUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Flights
   * const flight = await prisma.flight.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends FlightUpdateManyArgs>(args: Prisma.SelectSubset<T, FlightUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Flights and returns the data updated in the database.
   * @param {FlightUpdateManyAndReturnArgs} args - Arguments to update many Flights.
   * @example
   * // Update many Flights
   * const flight = await prisma.flight.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Flights and only return the `id`
   * const flightWithIdOnly = await prisma.flight.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends FlightUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, FlightUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FlightPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Flight.
   * @param {FlightUpsertArgs} args - Arguments to update or create a Flight.
   * @example
   * // Update or create a Flight
   * const flight = await prisma.flight.upsert({
   *   create: {
   *     // ... data to create a Flight
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Flight we want to update
   *   }
   * })
   */
  upsert<T extends FlightUpsertArgs>(args: Prisma.SelectSubset<T, FlightUpsertArgs<ExtArgs>>): Prisma.Prisma__FlightClient<runtime.Types.Result.GetResult<Prisma.$FlightPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Flights.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FlightCountArgs} args - Arguments to filter Flights to count.
   * @example
   * // Count the number of Flights
   * const count = await prisma.flight.count({
   *   where: {
   *     // ... the filter for the Flights we want to count
   *   }
   * })
  **/
  count<T extends FlightCountArgs>(
    args?: Prisma.Subset<T, FlightCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], FlightCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Flight.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FlightAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends FlightAggregateArgs>(args: Prisma.Subset<T, FlightAggregateArgs>): Prisma.PrismaPromise<GetFlightAggregateType<T>>

  /**
   * Group by Flight.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FlightGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends FlightGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: FlightGroupByArgs['orderBy'] }
      : { orderBy?: FlightGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, FlightGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetFlightGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Flight model
 */
readonly fields: FlightFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Flight.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__FlightClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  passengers<T extends Prisma.Flight$passengersArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Flight$passengersArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PassengerPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  origin<T extends Prisma.AirportDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.AirportDefaultArgs<ExtArgs>>): Prisma.Prisma__AirportClient<runtime.Types.Result.GetResult<Prisma.$AirportPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  destination<T extends Prisma.AirportDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.AirportDefaultArgs<ExtArgs>>): Prisma.Prisma__AirportClient<runtime.Types.Result.GetResult<Prisma.$AirportPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  plane<T extends Prisma.PlaneDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.PlaneDefaultArgs<ExtArgs>>): Prisma.Prisma__PlaneClient<runtime.Types.Result.GetResult<Prisma.$PlanePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Flight model
 */
export interface FlightFieldRefs {
  readonly id: Prisma.FieldRef<"Flight", 'String'>
  readonly flightNumber: Prisma.FieldRef<"Flight", 'String'>
  readonly departureTime: Prisma.FieldRef<"Flight", 'DateTime'>
  readonly arrivalTime: Prisma.FieldRef<"Flight", 'DateTime'>
  readonly originId: Prisma.FieldRef<"Flight", 'String'>
  readonly destinationId: Prisma.FieldRef<"Flight", 'String'>
  readonly planeId: Prisma.FieldRef<"Flight", 'String'>
}
    

// Custom InputTypes
/**
 * Flight findUnique
 */
export type FlightFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Flight
   */
  select?: Prisma.FlightSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Flight
   */
  omit?: Prisma.FlightOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FlightInclude<ExtArgs> | null
  /**
   * Filter, which Flight to fetch.
   */
  where: Prisma.FlightWhereUniqueInput
}

/**
 * Flight findUniqueOrThrow
 */
export type FlightFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Flight
   */
  select?: Prisma.FlightSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Flight
   */
  omit?: Prisma.FlightOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FlightInclude<ExtArgs> | null
  /**
   * Filter, which Flight to fetch.
   */
  where: Prisma.FlightWhereUniqueInput
}

/**
 * Flight findFirst
 */
export type FlightFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Flight
   */
  select?: Prisma.FlightSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Flight
   */
  omit?: Prisma.FlightOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FlightInclude<ExtArgs> | null
  /**
   * Filter, which Flight to fetch.
   */
  where?: Prisma.FlightWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Flights to fetch.
   */
  orderBy?: Prisma.FlightOrderByWithRelationInput | Prisma.FlightOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Flights.
   */
  cursor?: Prisma.FlightWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Flights from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Flights.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Flights.
   */
  distinct?: Prisma.FlightScalarFieldEnum | Prisma.FlightScalarFieldEnum[]
}

/**
 * Flight findFirstOrThrow
 */
export type FlightFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Flight
   */
  select?: Prisma.FlightSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Flight
   */
  omit?: Prisma.FlightOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FlightInclude<ExtArgs> | null
  /**
   * Filter, which Flight to fetch.
   */
  where?: Prisma.FlightWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Flights to fetch.
   */
  orderBy?: Prisma.FlightOrderByWithRelationInput | Prisma.FlightOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Flights.
   */
  cursor?: Prisma.FlightWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Flights from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Flights.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Flights.
   */
  distinct?: Prisma.FlightScalarFieldEnum | Prisma.FlightScalarFieldEnum[]
}

/**
 * Flight findMany
 */
export type FlightFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Flight
   */
  select?: Prisma.FlightSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Flight
   */
  omit?: Prisma.FlightOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FlightInclude<ExtArgs> | null
  /**
   * Filter, which Flights to fetch.
   */
  where?: Prisma.FlightWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Flights to fetch.
   */
  orderBy?: Prisma.FlightOrderByWithRelationInput | Prisma.FlightOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Flights.
   */
  cursor?: Prisma.FlightWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Flights from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Flights.
   */
  skip?: number
  distinct?: Prisma.FlightScalarFieldEnum | Prisma.FlightScalarFieldEnum[]
}

/**
 * Flight create
 */
export type FlightCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Flight
   */
  select?: Prisma.FlightSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Flight
   */
  omit?: Prisma.FlightOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FlightInclude<ExtArgs> | null
  /**
   * The data needed to create a Flight.
   */
  data: Prisma.XOR<Prisma.FlightCreateInput, Prisma.FlightUncheckedCreateInput>
}

/**
 * Flight createMany
 */
export type FlightCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Flights.
   */
  data: Prisma.FlightCreateManyInput | Prisma.FlightCreateManyInput[]
}

/**
 * Flight createManyAndReturn
 */
export type FlightCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Flight
   */
  select?: Prisma.FlightSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Flight
   */
  omit?: Prisma.FlightOmit<ExtArgs> | null
  /**
   * The data used to create many Flights.
   */
  data: Prisma.FlightCreateManyInput | Prisma.FlightCreateManyInput[]
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FlightIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Flight update
 */
export type FlightUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Flight
   */
  select?: Prisma.FlightSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Flight
   */
  omit?: Prisma.FlightOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FlightInclude<ExtArgs> | null
  /**
   * The data needed to update a Flight.
   */
  data: Prisma.XOR<Prisma.FlightUpdateInput, Prisma.FlightUncheckedUpdateInput>
  /**
   * Choose, which Flight to update.
   */
  where: Prisma.FlightWhereUniqueInput
}

/**
 * Flight updateMany
 */
export type FlightUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Flights.
   */
  data: Prisma.XOR<Prisma.FlightUpdateManyMutationInput, Prisma.FlightUncheckedUpdateManyInput>
  /**
   * Filter which Flights to update
   */
  where?: Prisma.FlightWhereInput
  /**
   * Limit how many Flights to update.
   */
  limit?: number
}

/**
 * Flight updateManyAndReturn
 */
export type FlightUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Flight
   */
  select?: Prisma.FlightSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Flight
   */
  omit?: Prisma.FlightOmit<ExtArgs> | null
  /**
   * The data used to update Flights.
   */
  data: Prisma.XOR<Prisma.FlightUpdateManyMutationInput, Prisma.FlightUncheckedUpdateManyInput>
  /**
   * Filter which Flights to update
   */
  where?: Prisma.FlightWhereInput
  /**
   * Limit how many Flights to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FlightIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Flight upsert
 */
export type FlightUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Flight
   */
  select?: Prisma.FlightSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Flight
   */
  omit?: Prisma.FlightOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FlightInclude<ExtArgs> | null
  /**
   * The filter to search for the Flight to update in case it exists.
   */
  where: Prisma.FlightWhereUniqueInput
  /**
   * In case the Flight found by the `where` argument doesn't exist, create a new Flight with this data.
   */
  create: Prisma.XOR<Prisma.FlightCreateInput, Prisma.FlightUncheckedCreateInput>
  /**
   * In case the Flight was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.FlightUpdateInput, Prisma.FlightUncheckedUpdateInput>
}

/**
 * Flight delete
 */
export type FlightDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Flight
   */
  select?: Prisma.FlightSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Flight
   */
  omit?: Prisma.FlightOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FlightInclude<ExtArgs> | null
  /**
   * Filter which Flight to delete.
   */
  where: Prisma.FlightWhereUniqueInput
}

/**
 * Flight deleteMany
 */
export type FlightDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Flights to delete
   */
  where?: Prisma.FlightWhereInput
  /**
   * Limit how many Flights to delete.
   */
  limit?: number
}

/**
 * Flight.passengers
 */
export type Flight$passengersArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Passenger
   */
  select?: Prisma.PassengerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Passenger
   */
  omit?: Prisma.PassengerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PassengerInclude<ExtArgs> | null
  where?: Prisma.PassengerWhereInput
  orderBy?: Prisma.PassengerOrderByWithRelationInput | Prisma.PassengerOrderByWithRelationInput[]
  cursor?: Prisma.PassengerWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.PassengerScalarFieldEnum | Prisma.PassengerScalarFieldEnum[]
}

/**
 * Flight without action
 */
export type FlightDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Flight
   */
  select?: Prisma.FlightSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Flight
   */
  omit?: Prisma.FlightOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FlightInclude<ExtArgs> | null
}
