
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck 
/*
 * This file exports the `Plane` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model Plane
 * 
 */
export type PlaneModel = runtime.Types.Result.DefaultSelection<Prisma.$PlanePayload>

export type AggregatePlane = {
  _count: PlaneCountAggregateOutputType | null
  _avg: PlaneAvgAggregateOutputType | null
  _sum: PlaneSumAggregateOutputType | null
  _min: PlaneMinAggregateOutputType | null
  _max: PlaneMaxAggregateOutputType | null
}

export type PlaneAvgAggregateOutputType = {
  capacity: number | null
}

export type PlaneSumAggregateOutputType = {
  capacity: number | null
}

export type PlaneMinAggregateOutputType = {
  id: string | null
  model: string | null
  capacity: number | null
}

export type PlaneMaxAggregateOutputType = {
  id: string | null
  model: string | null
  capacity: number | null
}

export type PlaneCountAggregateOutputType = {
  id: number
  model: number
  capacity: number
  _all: number
}


export type PlaneAvgAggregateInputType = {
  capacity?: true
}

export type PlaneSumAggregateInputType = {
  capacity?: true
}

export type PlaneMinAggregateInputType = {
  id?: true
  model?: true
  capacity?: true
}

export type PlaneMaxAggregateInputType = {
  id?: true
  model?: true
  capacity?: true
}

export type PlaneCountAggregateInputType = {
  id?: true
  model?: true
  capacity?: true
  _all?: true
}

export type PlaneAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Plane to aggregate.
   */
  where?: Prisma.PlaneWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Planes to fetch.
   */
  orderBy?: Prisma.PlaneOrderByWithRelationInput | Prisma.PlaneOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.PlaneWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Planes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Planes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Planes
  **/
  _count?: true | PlaneCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: PlaneAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: PlaneSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: PlaneMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: PlaneMaxAggregateInputType
}

export type GetPlaneAggregateType<T extends PlaneAggregateArgs> = {
      [P in keyof T & keyof AggregatePlane]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregatePlane[P]>
    : Prisma.GetScalarType<T[P], AggregatePlane[P]>
}




export type PlaneGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.PlaneWhereInput
  orderBy?: Prisma.PlaneOrderByWithAggregationInput | Prisma.PlaneOrderByWithAggregationInput[]
  by: Prisma.PlaneScalarFieldEnum[] | Prisma.PlaneScalarFieldEnum
  having?: Prisma.PlaneScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: PlaneCountAggregateInputType | true
  _avg?: PlaneAvgAggregateInputType
  _sum?: PlaneSumAggregateInputType
  _min?: PlaneMinAggregateInputType
  _max?: PlaneMaxAggregateInputType
}

export type PlaneGroupByOutputType = {
  id: string
  model: string
  capacity: number
  _count: PlaneCountAggregateOutputType | null
  _avg: PlaneAvgAggregateOutputType | null
  _sum: PlaneSumAggregateOutputType | null
  _min: PlaneMinAggregateOutputType | null
  _max: PlaneMaxAggregateOutputType | null
}

type GetPlaneGroupByPayload<T extends PlaneGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<PlaneGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof PlaneGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], PlaneGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], PlaneGroupByOutputType[P]>
      }
    >
  >



export type PlaneWhereInput = {
  AND?: Prisma.PlaneWhereInput | Prisma.PlaneWhereInput[]
  OR?: Prisma.PlaneWhereInput[]
  NOT?: Prisma.PlaneWhereInput | Prisma.PlaneWhereInput[]
  id?: Prisma.StringFilter<"Plane"> | string
  model?: Prisma.StringFilter<"Plane"> | string
  capacity?: Prisma.IntFilter<"Plane"> | number
  flights?: Prisma.FlightListRelationFilter
}

export type PlaneOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  model?: Prisma.SortOrder
  capacity?: Prisma.SortOrder
  flights?: Prisma.FlightOrderByRelationAggregateInput
}

export type PlaneWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.PlaneWhereInput | Prisma.PlaneWhereInput[]
  OR?: Prisma.PlaneWhereInput[]
  NOT?: Prisma.PlaneWhereInput | Prisma.PlaneWhereInput[]
  model?: Prisma.StringFilter<"Plane"> | string
  capacity?: Prisma.IntFilter<"Plane"> | number
  flights?: Prisma.FlightListRelationFilter
}, "id">

export type PlaneOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  model?: Prisma.SortOrder
  capacity?: Prisma.SortOrder
  _count?: Prisma.PlaneCountOrderByAggregateInput
  _avg?: Prisma.PlaneAvgOrderByAggregateInput
  _max?: Prisma.PlaneMaxOrderByAggregateInput
  _min?: Prisma.PlaneMinOrderByAggregateInput
  _sum?: Prisma.PlaneSumOrderByAggregateInput
}

export type PlaneScalarWhereWithAggregatesInput = {
  AND?: Prisma.PlaneScalarWhereWithAggregatesInput | Prisma.PlaneScalarWhereWithAggregatesInput[]
  OR?: Prisma.PlaneScalarWhereWithAggregatesInput[]
  NOT?: Prisma.PlaneScalarWhereWithAggregatesInput | Prisma.PlaneScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Plane"> | string
  model?: Prisma.StringWithAggregatesFilter<"Plane"> | string
  capacity?: Prisma.IntWithAggregatesFilter<"Plane"> | number
}

export type PlaneCreateInput = {
  id?: string
  model: string
  capacity: number
  flights?: Prisma.FlightCreateNestedManyWithoutPlaneInput
}

export type PlaneUncheckedCreateInput = {
  id?: string
  model: string
  capacity: number
  flights?: Prisma.FlightUncheckedCreateNestedManyWithoutPlaneInput
}

export type PlaneUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  model?: Prisma.StringFieldUpdateOperationsInput | string
  capacity?: Prisma.IntFieldUpdateOperationsInput | number
  flights?: Prisma.FlightUpdateManyWithoutPlaneNestedInput
}

export type PlaneUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  model?: Prisma.StringFieldUpdateOperationsInput | string
  capacity?: Prisma.IntFieldUpdateOperationsInput | number
  flights?: Prisma.FlightUncheckedUpdateManyWithoutPlaneNestedInput
}

export type PlaneCreateManyInput = {
  id?: string
  model: string
  capacity: number
}

export type PlaneUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  model?: Prisma.StringFieldUpdateOperationsInput | string
  capacity?: Prisma.IntFieldUpdateOperationsInput | number
}

export type PlaneUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  model?: Prisma.StringFieldUpdateOperationsInput | string
  capacity?: Prisma.IntFieldUpdateOperationsInput | number
}

export type PlaneScalarRelationFilter = {
  is?: Prisma.PlaneWhereInput
  isNot?: Prisma.PlaneWhereInput
}

export type PlaneCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  model?: Prisma.SortOrder
  capacity?: Prisma.SortOrder
}

export type PlaneAvgOrderByAggregateInput = {
  capacity?: Prisma.SortOrder
}

export type PlaneMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  model?: Prisma.SortOrder
  capacity?: Prisma.SortOrder
}

export type PlaneMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  model?: Prisma.SortOrder
  capacity?: Prisma.SortOrder
}

export type PlaneSumOrderByAggregateInput = {
  capacity?: Prisma.SortOrder
}

export type PlaneCreateNestedOneWithoutFlightsInput = {
  create?: Prisma.XOR<Prisma.PlaneCreateWithoutFlightsInput, Prisma.PlaneUncheckedCreateWithoutFlightsInput>
  connectOrCreate?: Prisma.PlaneCreateOrConnectWithoutFlightsInput
  connect?: Prisma.PlaneWhereUniqueInput
}

export type PlaneUpdateOneRequiredWithoutFlightsNestedInput = {
  create?: Prisma.XOR<Prisma.PlaneCreateWithoutFlightsInput, Prisma.PlaneUncheckedCreateWithoutFlightsInput>
  connectOrCreate?: Prisma.PlaneCreateOrConnectWithoutFlightsInput
  upsert?: Prisma.PlaneUpsertWithoutFlightsInput
  connect?: Prisma.PlaneWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.PlaneUpdateToOneWithWhereWithoutFlightsInput, Prisma.PlaneUpdateWithoutFlightsInput>, Prisma.PlaneUncheckedUpdateWithoutFlightsInput>
}

export type IntFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type PlaneCreateWithoutFlightsInput = {
  id?: string
  model: string
  capacity: number
}

export type PlaneUncheckedCreateWithoutFlightsInput = {
  id?: string
  model: string
  capacity: number
}

export type PlaneCreateOrConnectWithoutFlightsInput = {
  where: Prisma.PlaneWhereUniqueInput
  create: Prisma.XOR<Prisma.PlaneCreateWithoutFlightsInput, Prisma.PlaneUncheckedCreateWithoutFlightsInput>
}

export type PlaneUpsertWithoutFlightsInput = {
  update: Prisma.XOR<Prisma.PlaneUpdateWithoutFlightsInput, Prisma.PlaneUncheckedUpdateWithoutFlightsInput>
  create: Prisma.XOR<Prisma.PlaneCreateWithoutFlightsInput, Prisma.PlaneUncheckedCreateWithoutFlightsInput>
  where?: Prisma.PlaneWhereInput
}

export type PlaneUpdateToOneWithWhereWithoutFlightsInput = {
  where?: Prisma.PlaneWhereInput
  data: Prisma.XOR<Prisma.PlaneUpdateWithoutFlightsInput, Prisma.PlaneUncheckedUpdateWithoutFlightsInput>
}

export type PlaneUpdateWithoutFlightsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  model?: Prisma.StringFieldUpdateOperationsInput | string
  capacity?: Prisma.IntFieldUpdateOperationsInput | number
}

export type PlaneUncheckedUpdateWithoutFlightsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  model?: Prisma.StringFieldUpdateOperationsInput | string
  capacity?: Prisma.IntFieldUpdateOperationsInput | number
}


/**
 * Count Type PlaneCountOutputType
 */

export type PlaneCountOutputType = {
  flights: number
}

export type PlaneCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  flights?: boolean | PlaneCountOutputTypeCountFlightsArgs
}

/**
 * PlaneCountOutputType without action
 */
export type PlaneCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PlaneCountOutputType
   */
  select?: Prisma.PlaneCountOutputTypeSelect<ExtArgs> | null
}

/**
 * PlaneCountOutputType without action
 */
export type PlaneCountOutputTypeCountFlightsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.FlightWhereInput
}


export type PlaneSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  model?: boolean
  capacity?: boolean
  flights?: boolean | Prisma.Plane$flightsArgs<ExtArgs>
  _count?: boolean | Prisma.PlaneCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["plane"]>

export type PlaneSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  model?: boolean
  capacity?: boolean
}, ExtArgs["result"]["plane"]>

export type PlaneSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  model?: boolean
  capacity?: boolean
}, ExtArgs["result"]["plane"]>

export type PlaneSelectScalar = {
  id?: boolean
  model?: boolean
  capacity?: boolean
}

export type PlaneOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "model" | "capacity", ExtArgs["result"]["plane"]>
export type PlaneInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  flights?: boolean | Prisma.Plane$flightsArgs<ExtArgs>
  _count?: boolean | Prisma.PlaneCountOutputTypeDefaultArgs<ExtArgs>
}
export type PlaneIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type PlaneIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $PlanePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Plane"
  objects: {
    flights: Prisma.$FlightPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    model: string
    capacity: number
  }, ExtArgs["result"]["plane"]>
  composites: {}
}

export type PlaneGetPayload<S extends boolean | null | undefined | PlaneDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$PlanePayload, S>

export type PlaneCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<PlaneFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: PlaneCountAggregateInputType | true
  }

export interface PlaneDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Plane'], meta: { name: 'Plane' } }
  /**
   * Find zero or one Plane that matches the filter.
   * @param {PlaneFindUniqueArgs} args - Arguments to find a Plane
   * @example
   * // Get one Plane
   * const plane = await prisma.plane.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends PlaneFindUniqueArgs>(args: Prisma.SelectSubset<T, PlaneFindUniqueArgs<ExtArgs>>): Prisma.Prisma__PlaneClient<runtime.Types.Result.GetResult<Prisma.$PlanePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Plane that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {PlaneFindUniqueOrThrowArgs} args - Arguments to find a Plane
   * @example
   * // Get one Plane
   * const plane = await prisma.plane.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends PlaneFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, PlaneFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__PlaneClient<runtime.Types.Result.GetResult<Prisma.$PlanePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Plane that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PlaneFindFirstArgs} args - Arguments to find a Plane
   * @example
   * // Get one Plane
   * const plane = await prisma.plane.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends PlaneFindFirstArgs>(args?: Prisma.SelectSubset<T, PlaneFindFirstArgs<ExtArgs>>): Prisma.Prisma__PlaneClient<runtime.Types.Result.GetResult<Prisma.$PlanePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Plane that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PlaneFindFirstOrThrowArgs} args - Arguments to find a Plane
   * @example
   * // Get one Plane
   * const plane = await prisma.plane.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends PlaneFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, PlaneFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__PlaneClient<runtime.Types.Result.GetResult<Prisma.$PlanePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Planes that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PlaneFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Planes
   * const planes = await prisma.plane.findMany()
   * 
   * // Get first 10 Planes
   * const planes = await prisma.plane.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const planeWithIdOnly = await prisma.plane.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends PlaneFindManyArgs>(args?: Prisma.SelectSubset<T, PlaneFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PlanePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Plane.
   * @param {PlaneCreateArgs} args - Arguments to create a Plane.
   * @example
   * // Create one Plane
   * const Plane = await prisma.plane.create({
   *   data: {
   *     // ... data to create a Plane
   *   }
   * })
   * 
   */
  create<T extends PlaneCreateArgs>(args: Prisma.SelectSubset<T, PlaneCreateArgs<ExtArgs>>): Prisma.Prisma__PlaneClient<runtime.Types.Result.GetResult<Prisma.$PlanePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Planes.
   * @param {PlaneCreateManyArgs} args - Arguments to create many Planes.
   * @example
   * // Create many Planes
   * const plane = await prisma.plane.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends PlaneCreateManyArgs>(args?: Prisma.SelectSubset<T, PlaneCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Planes and returns the data saved in the database.
   * @param {PlaneCreateManyAndReturnArgs} args - Arguments to create many Planes.
   * @example
   * // Create many Planes
   * const plane = await prisma.plane.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Planes and only return the `id`
   * const planeWithIdOnly = await prisma.plane.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends PlaneCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, PlaneCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PlanePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Plane.
   * @param {PlaneDeleteArgs} args - Arguments to delete one Plane.
   * @example
   * // Delete one Plane
   * const Plane = await prisma.plane.delete({
   *   where: {
   *     // ... filter to delete one Plane
   *   }
   * })
   * 
   */
  delete<T extends PlaneDeleteArgs>(args: Prisma.SelectSubset<T, PlaneDeleteArgs<ExtArgs>>): Prisma.Prisma__PlaneClient<runtime.Types.Result.GetResult<Prisma.$PlanePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Plane.
   * @param {PlaneUpdateArgs} args - Arguments to update one Plane.
   * @example
   * // Update one Plane
   * const plane = await prisma.plane.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends PlaneUpdateArgs>(args: Prisma.SelectSubset<T, PlaneUpdateArgs<ExtArgs>>): Prisma.Prisma__PlaneClient<runtime.Types.Result.GetResult<Prisma.$PlanePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Planes.
   * @param {PlaneDeleteManyArgs} args - Arguments to filter Planes to delete.
   * @example
   * // Delete a few Planes
   * const { count } = await prisma.plane.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends PlaneDeleteManyArgs>(args?: Prisma.SelectSubset<T, PlaneDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Planes.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PlaneUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Planes
   * const plane = await prisma.plane.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends PlaneUpdateManyArgs>(args: Prisma.SelectSubset<T, PlaneUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Planes and returns the data updated in the database.
   * @param {PlaneUpdateManyAndReturnArgs} args - Arguments to update many Planes.
   * @example
   * // Update many Planes
   * const plane = await prisma.plane.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Planes and only return the `id`
   * const planeWithIdOnly = await prisma.plane.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends PlaneUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, PlaneUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PlanePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Plane.
   * @param {PlaneUpsertArgs} args - Arguments to update or create a Plane.
   * @example
   * // Update or create a Plane
   * const plane = await prisma.plane.upsert({
   *   create: {
   *     // ... data to create a Plane
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Plane we want to update
   *   }
   * })
   */
  upsert<T extends PlaneUpsertArgs>(args: Prisma.SelectSubset<T, PlaneUpsertArgs<ExtArgs>>): Prisma.Prisma__PlaneClient<runtime.Types.Result.GetResult<Prisma.$PlanePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Planes.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PlaneCountArgs} args - Arguments to filter Planes to count.
   * @example
   * // Count the number of Planes
   * const count = await prisma.plane.count({
   *   where: {
   *     // ... the filter for the Planes we want to count
   *   }
   * })
  **/
  count<T extends PlaneCountArgs>(
    args?: Prisma.Subset<T, PlaneCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], PlaneCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Plane.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PlaneAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends PlaneAggregateArgs>(args: Prisma.Subset<T, PlaneAggregateArgs>): Prisma.PrismaPromise<GetPlaneAggregateType<T>>

  /**
   * Group by Plane.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PlaneGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends PlaneGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: PlaneGroupByArgs['orderBy'] }
      : { orderBy?: PlaneGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, PlaneGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetPlaneGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Plane model
 */
readonly fields: PlaneFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Plane.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__PlaneClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  flights<T extends Prisma.Plane$flightsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Plane$flightsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FlightPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Plane model
 */
export interface PlaneFieldRefs {
  readonly id: Prisma.FieldRef<"Plane", 'String'>
  readonly model: Prisma.FieldRef<"Plane", 'String'>
  readonly capacity: Prisma.FieldRef<"Plane", 'Int'>
}
    

// Custom InputTypes
/**
 * Plane findUnique
 */
export type PlaneFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Plane
   */
  select?: Prisma.PlaneSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Plane
   */
  omit?: Prisma.PlaneOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PlaneInclude<ExtArgs> | null
  /**
   * Filter, which Plane to fetch.
   */
  where: Prisma.PlaneWhereUniqueInput
}

/**
 * Plane findUniqueOrThrow
 */
export type PlaneFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Plane
   */
  select?: Prisma.PlaneSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Plane
   */
  omit?: Prisma.PlaneOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PlaneInclude<ExtArgs> | null
  /**
   * Filter, which Plane to fetch.
   */
  where: Prisma.PlaneWhereUniqueInput
}

/**
 * Plane findFirst
 */
export type PlaneFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Plane
   */
  select?: Prisma.PlaneSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Plane
   */
  omit?: Prisma.PlaneOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PlaneInclude<ExtArgs> | null
  /**
   * Filter, which Plane to fetch.
   */
  where?: Prisma.PlaneWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Planes to fetch.
   */
  orderBy?: Prisma.PlaneOrderByWithRelationInput | Prisma.PlaneOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Planes.
   */
  cursor?: Prisma.PlaneWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Planes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Planes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Planes.
   */
  distinct?: Prisma.PlaneScalarFieldEnum | Prisma.PlaneScalarFieldEnum[]
}

/**
 * Plane findFirstOrThrow
 */
export type PlaneFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Plane
   */
  select?: Prisma.PlaneSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Plane
   */
  omit?: Prisma.PlaneOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PlaneInclude<ExtArgs> | null
  /**
   * Filter, which Plane to fetch.
   */
  where?: Prisma.PlaneWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Planes to fetch.
   */
  orderBy?: Prisma.PlaneOrderByWithRelationInput | Prisma.PlaneOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Planes.
   */
  cursor?: Prisma.PlaneWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Planes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Planes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Planes.
   */
  distinct?: Prisma.PlaneScalarFieldEnum | Prisma.PlaneScalarFieldEnum[]
}

/**
 * Plane findMany
 */
export type PlaneFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Plane
   */
  select?: Prisma.PlaneSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Plane
   */
  omit?: Prisma.PlaneOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PlaneInclude<ExtArgs> | null
  /**
   * Filter, which Planes to fetch.
   */
  where?: Prisma.PlaneWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Planes to fetch.
   */
  orderBy?: Prisma.PlaneOrderByWithRelationInput | Prisma.PlaneOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Planes.
   */
  cursor?: Prisma.PlaneWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Planes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Planes.
   */
  skip?: number
  distinct?: Prisma.PlaneScalarFieldEnum | Prisma.PlaneScalarFieldEnum[]
}

/**
 * Plane create
 */
export type PlaneCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Plane
   */
  select?: Prisma.PlaneSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Plane
   */
  omit?: Prisma.PlaneOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PlaneInclude<ExtArgs> | null
  /**
   * The data needed to create a Plane.
   */
  data: Prisma.XOR<Prisma.PlaneCreateInput, Prisma.PlaneUncheckedCreateInput>
}

/**
 * Plane createMany
 */
export type PlaneCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Planes.
   */
  data: Prisma.PlaneCreateManyInput | Prisma.PlaneCreateManyInput[]
}

/**
 * Plane createManyAndReturn
 */
export type PlaneCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Plane
   */
  select?: Prisma.PlaneSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Plane
   */
  omit?: Prisma.PlaneOmit<ExtArgs> | null
  /**
   * The data used to create many Planes.
   */
  data: Prisma.PlaneCreateManyInput | Prisma.PlaneCreateManyInput[]
}

/**
 * Plane update
 */
export type PlaneUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Plane
   */
  select?: Prisma.PlaneSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Plane
   */
  omit?: Prisma.PlaneOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PlaneInclude<ExtArgs> | null
  /**
   * The data needed to update a Plane.
   */
  data: Prisma.XOR<Prisma.PlaneUpdateInput, Prisma.PlaneUncheckedUpdateInput>
  /**
   * Choose, which Plane to update.
   */
  where: Prisma.PlaneWhereUniqueInput
}

/**
 * Plane updateMany
 */
export type PlaneUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Planes.
   */
  data: Prisma.XOR<Prisma.PlaneUpdateManyMutationInput, Prisma.PlaneUncheckedUpdateManyInput>
  /**
   * Filter which Planes to update
   */
  where?: Prisma.PlaneWhereInput
  /**
   * Limit how many Planes to update.
   */
  limit?: number
}

/**
 * Plane updateManyAndReturn
 */
export type PlaneUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Plane
   */
  select?: Prisma.PlaneSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Plane
   */
  omit?: Prisma.PlaneOmit<ExtArgs> | null
  /**
   * The data used to update Planes.
   */
  data: Prisma.XOR<Prisma.PlaneUpdateManyMutationInput, Prisma.PlaneUncheckedUpdateManyInput>
  /**
   * Filter which Planes to update
   */
  where?: Prisma.PlaneWhereInput
  /**
   * Limit how many Planes to update.
   */
  limit?: number
}

/**
 * Plane upsert
 */
export type PlaneUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Plane
   */
  select?: Prisma.PlaneSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Plane
   */
  omit?: Prisma.PlaneOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PlaneInclude<ExtArgs> | null
  /**
   * The filter to search for the Plane to update in case it exists.
   */
  where: Prisma.PlaneWhereUniqueInput
  /**
   * In case the Plane found by the `where` argument doesn't exist, create a new Plane with this data.
   */
  create: Prisma.XOR<Prisma.PlaneCreateInput, Prisma.PlaneUncheckedCreateInput>
  /**
   * In case the Plane was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.PlaneUpdateInput, Prisma.PlaneUncheckedUpdateInput>
}

/**
 * Plane delete
 */
export type PlaneDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Plane
   */
  select?: Prisma.PlaneSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Plane
   */
  omit?: Prisma.PlaneOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PlaneInclude<ExtArgs> | null
  /**
   * Filter which Plane to delete.
   */
  where: Prisma.PlaneWhereUniqueInput
}

/**
 * Plane deleteMany
 */
export type PlaneDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Planes to delete
   */
  where?: Prisma.PlaneWhereInput
  /**
   * Limit how many Planes to delete.
   */
  limit?: number
}

/**
 * Plane.flights
 */
export type Plane$flightsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Flight
   */
  select?: Prisma.FlightSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Flight
   */
  omit?: Prisma.FlightOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FlightInclude<ExtArgs> | null
  where?: Prisma.FlightWhereInput
  orderBy?: Prisma.FlightOrderByWithRelationInput | Prisma.FlightOrderByWithRelationInput[]
  cursor?: Prisma.FlightWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.FlightScalarFieldEnum | Prisma.FlightScalarFieldEnum[]
}

/**
 * Plane without action
 */
export type PlaneDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Plane
   */
  select?: Prisma.PlaneSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Plane
   */
  omit?: Prisma.PlaneOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PlaneInclude<ExtArgs> | null
}
